version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
    networks:
      - mlqnet
  node:
    image: node-http-demo:1.0
    networks:
      mlqnet:
        aliases:
          - video-compress
networks:
  mlqnet:
